name: Building and testing
on:
  push:
    branches: [main]
jobs:
  backend_testing:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.9.x'
      - run: python -m pip install --upgrade pip
      - run: python -m pip install -r requirements.txt
      - run: python manage.py test
  frontend_testing:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.9.x'
      - run: python -m pip install --upgrade pip
      - run: python -m pip install -r requirements.txt
      - working-directory: ./
        run: python manage.py runserver
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - working-directory: ./frontend
        run: npm install
      - working-directory: ./frontend
        run: npm run dev
      - working-directory: ./frontend
        run: npm run test
      - working-directory: ./frontend
        run: npm run e2e