name: Building and testing
on:
  push:
    branches: [main]
jobs:
  backend_testing:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.9.x'
      - run: python -m pip install --upgrade pip
      - run: python -m pip install -r requirements.txt
      - run: python manage.py test
  frontend_testing:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - working-directory: ./frontend
        run: npm install
      - working-directory: ./frontend
        run: npm run dev
      - working-directory: ./frontend
        run: npm run test CreateRoomPage.test.js LogIn.test.js
  e2e_testing:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - working-directory: ./frontend
        run: npm install
      - uses: cypress-io/github-action@v2
        with:
          working-directory: ./frontend
          build: npm run dev
          start: npm start